version: '3'
services:
  frontend:
    build: ./frontend
    container_name: frontend
    command: yarn start
    ports:
      - 8080:8080
    depends_on:
      - api
    volumes:
     - ./frontend:/usr/src/frontend
     - /usr/src/frontend/node_modules
    environment:
      NODE_ENV: development

  api:
    build: ./api
    container_name: api
    command: yarn start
    ports:
      - 3000:3000
    depends_on:
      - mongo
    volumes:
      - ./api:/usr/src/api
      - /usr/src/api/node_modules
    links:
      - mongo
    environment:
      NODE_ENV: development
      EXPRESS_PORT: 3000
      MONGO: mongo

  mongo:
    image: mongo
    container_name: mongodb
    ports:
      - 27017:27017