const
    GET_ORDERS = 'GET_ORDERS',
    GET_COUNTRIES = 'GET_COUNTRIES',
    GET_CITIES = 'GET_CITIES',
    GET_PRODUCTS = 'GET_PRODUCTS',
    GET_AVAILABLE_USERS = 'GET_AVAILABLE_USERS',
    GET_USERS = 'GET_USERS',
    CHANGE_COUNTRY = 'CHANGE_COUNTRY',
    CHANGE_CITY = 'CHANGE_CITY',
    LOGIN = 'LOGIN',
    PLACE_ORDER = 'PLACE_ORDER',
    RESET = 'RESET'

export default {
    GET_ORDERS,
    GET_COUNTRIES,
    GET_CITIES,
    GET_PRODUCTS,
    GET_AVAILABLE_USERS,
    GET_USERS,
    CHANGE_COUNTRY,
    CHANGE_CITY,
    LOGIN,
    PLACE_ORDER,
    RESET
}