const
    GET_COUNTRIES = 'GET_COUNTRIES',
    GET_CITIES = 'GET_CITIES',
    GET_PRODUCTS = 'GET_PRODUCTS',
    GET_AVAILABLE_USERS = 'GET_AVAILABLE_USERS'

export default {
    GET_COUNTRIES,
    GET_CITIES,
    GET_PRODUCTS,
    GET_AVAILABLE_USERS
}